# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-02 02:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tblog', '0003_auto_20161102_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='body',
            field=models.TextField(),
        ),
    ]
